name: hyper_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  uuid: ^4.2.1
  flutter_image_compress: ^2.0.3
  cached_network_image: ^3.2.2
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  flutter_map: ^6.0.1
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^3.1.0
  flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  faker_dart: ^0.2.1
  syncfusion_flutter_charts: ^23.1.44
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
